In [1]:
import numpy as np
import biobeam


...choosing the best from the rest
/usr/local/lib64/python3.6/site-packages/pyopencl/cffi_cl.py:1521: CompilerWarning: Non-empty compiler output encountered. Set the environment variable PYOPENCL_COMPILER_OUTPUT=1 to see more.
  "to see more.", CompilerWarning)


In [3]:
# configure the system to calculate a volume of 8x8x8 microns

# shape = cube with a given size
# units = pixel axis length in microns
# lam = wavelength
u, ex, ey, ez = biobeam.focus_field_beam(
    shape=(80, 80, 80), 
    units=(0.1, 0.1, 0.1),
    lam=488, NA=[0.8, 0], 
    return_all_fields=True)


/usr/local/lib64/python3.6/site-packages/pyopencl/cffi_cl.py:1521: CompilerWarning: Non-empty compiler output encountered. Set the environment variable PYOPENCL_COMPILER_OUTPUT=1 to see more.
  "to see more.", CompilerWarning)


In [6]:
# save result to disc
fout=open('NA0.8_intensity.dat', 'wb')
fout.write(u)
fout.close()


[[[0.41602856 0.41603616 0.41604343 ... 0.41605106 0.41604343 0.41603616]
  [0.41603678 0.41604418 0.4160519  ... 0.4160591  0.4160519  0.41604418]
  [0.41604462 0.41605246 0.4160598  ... 0.41606697 0.4160598  0.41605246]
  ...
  [0.4160528  0.41606024 0.41606748 ... 0.41607442 0.41606748 0.41606024]
  [0.41604462 0.41605246 0.4160598  ... 0.41606697 0.4160598  0.41605246]
  [0.41603678 0.41604418 0.4160519  ... 0.4160591  0.4160519  0.41604418]]

 [[0.41602933 0.41603693 0.41604427 ... 0.4160512  0.41604427 0.41603693]
  [0.41603756 0.416045   0.41605225 ... 0.41605905 0.41605225 0.416045  ]
  [0.4160455  0.41605285 0.4160598  ... 0.41606742 0.4160598  0.41605285]
  ...
  [0.41605294 0.41606015 0.41606796 ... 0.41607526 0.41606796 0.41606015]
  [0.4160455  0.41605285 0.4160598  ... 0.41606742 0.4160598  0.41605285]
  [0.41603756 0.416045   0.41605225 ... 0.41605905 0.41605225 0.416045  ]]

 [[0.41602993 0.41603723 0.4160449  ... 0.4160515  0.4160449  0.41603723]
  [0.41603786 0.416045

Now we can open the NA0.8_intensity.dat in Fiji by using the menu File > Import > Raw an entering width=80, height=80 and number of images=80

In [11]:
# let's try again with a different pixel size (and thus larger field of view)
u, ex, ey, ez = biobeam.focus_field_beam(
    shape=(80, 80, 80), 
    units=(10, 10, 10),
    lam=488, NA=[0.8, 0], 
    return_all_fields=True)

# save result to disc
fout=open('NA0.8_intensity2.dat', 'wb')
fout.write(u)
fout.close()


/usr/local/lib64/python3.6/site-packages/pyopencl/cffi_cl.py:1521: CompilerWarning: Non-empty compiler output encountered. Set the environment variable PYOPENCL_COMPILER_OUTPUT=1 to see more.
  "to see more.", CompilerWarning)


Again, we should have a look at this dataset from Fiji

In [14]:
# let's try again with a different pixel size (and thus larger field of view)
u, ex, ey, ez = biobeam.focus_field_beam(
    shape=(80, 80, 80), 
    units=(100, 100, 100),
    lam=488, NA=[0.8, 0], 
    return_all_fields=True)

# save result to disc
fout=open('NA0.8_intensity3.raw', 'wb')
fout.write(u)
fout.close()





/usr/local/lib64/python3.6/site-packages/pyopencl/cffi_cl.py:1521: CompilerWarning: Non-empty compiler output encountered. Set the environment variable PYOPENCL_COMPILER_OUTPUT=1 to see more.
  "to see more.", CompilerWarning)


In [16]:
# Bessel beams
u, ex, ey, ez = biobeam.focus_field_beam(
    shape=(80, 80, 80), 
    units=(100, 100, 100),
    lam=488, NA=[0.8, 0.7], 
    return_all_fields=True)

# save result to disc
fout=open('NA0.8_0.7_intensity_bessel.raw', 'wb')
fout.write(u)
fout.close()

/usr/local/lib64/python3.6/site-packages/pyopencl/cffi_cl.py:1521: CompilerWarning: Non-empty compiler output encountered. Set the environment variable PYOPENCL_COMPILER_OUTPUT=1 to see more.
  "to see more.", CompilerWarning)
